# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
export ZSH="/home/dcorral/.oh-my-zsh"
ZSH_THEME="agnoster"
plugins=(
	web-search
	copyfile
	extract
	wd
	docker
	docker-compose
	sudo
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh

